// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/RcppBandicoot.h"
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// gpu_initialize
void gpu_initialize(std::string type, bool print_info);
RcppExport SEXP _RcppBandicoot_gpu_initialize(SEXP typeSEXP, SEXP print_infoSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    Rcpp::traits::input_parameter< bool >::type print_info(print_infoSEXP);
    gpu_initialize(type, print_info);
    return R_NilValue;
END_RCPP
}
// bandicoot_version
void bandicoot_version();
RcppExport SEXP _RcppBandicoot_bandicoot_version() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    bandicoot_version();
    return R_NilValue;
END_RCPP
}
// gpu_matrix_multiply
coot::fmat gpu_matrix_multiply(const coot::fmat& A, const coot::fmat& B);
RcppExport SEXP _RcppBandicoot_gpu_matrix_multiply(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const coot::fmat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const coot::fmat& >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(gpu_matrix_multiply(A, B));
    return rcpp_result_gen;
END_RCPP
}
// gpu_transpose
coot::fmat gpu_transpose(const coot::fmat& A);
RcppExport SEXP _RcppBandicoot_gpu_transpose(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const coot::fmat& >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(gpu_transpose(A));
    return rcpp_result_gen;
END_RCPP
}
// gpu_matrix_add
coot::fmat gpu_matrix_add(const coot::fmat& A, const coot::fmat& B);
RcppExport SEXP _RcppBandicoot_gpu_matrix_add(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const coot::fmat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const coot::fmat& >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(gpu_matrix_add(A, B));
    return rcpp_result_gen;
END_RCPP
}
// gpu_element_square
coot::mat gpu_element_square(const coot::mat& A);
RcppExport SEXP _RcppBandicoot_gpu_element_square(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const coot::mat& >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(gpu_element_square(A));
    return rcpp_result_gen;
END_RCPP
}
// gpu_sum
double gpu_sum(const coot::fmat& A);
RcppExport SEXP _RcppBandicoot_gpu_sum(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const coot::fmat& >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(gpu_sum(A));
    return rcpp_result_gen;
END_RCPP
}
// gpu_mean
double gpu_mean(const coot::fmat& A);
RcppExport SEXP _RcppBandicoot_gpu_mean(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const coot::fmat& >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(gpu_mean(A));
    return rcpp_result_gen;
END_RCPP
}
// gpu_eye
coot::fmat gpu_eye(int n);
RcppExport SEXP _RcppBandicoot_gpu_eye(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(gpu_eye(n));
    return rcpp_result_gen;
END_RCPP
}
// gpu_randu
coot::fmat gpu_randu(int n_rows, int n_cols);
RcppExport SEXP _RcppBandicoot_gpu_randu(SEXP n_rowsSEXP, SEXP n_colsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n_rows(n_rowsSEXP);
    Rcpp::traits::input_parameter< int >::type n_cols(n_colsSEXP);
    rcpp_result_gen = Rcpp::wrap(gpu_randu(n_rows, n_cols));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RcppBandicoot_gpu_initialize", (DL_FUNC) &_RcppBandicoot_gpu_initialize, 2},
    {"_RcppBandicoot_bandicoot_version", (DL_FUNC) &_RcppBandicoot_bandicoot_version, 0},
    {"_RcppBandicoot_gpu_matrix_multiply", (DL_FUNC) &_RcppBandicoot_gpu_matrix_multiply, 2},
    {"_RcppBandicoot_gpu_transpose", (DL_FUNC) &_RcppBandicoot_gpu_transpose, 1},
    {"_RcppBandicoot_gpu_matrix_add", (DL_FUNC) &_RcppBandicoot_gpu_matrix_add, 2},
    {"_RcppBandicoot_gpu_element_square", (DL_FUNC) &_RcppBandicoot_gpu_element_square, 1},
    {"_RcppBandicoot_gpu_sum", (DL_FUNC) &_RcppBandicoot_gpu_sum, 1},
    {"_RcppBandicoot_gpu_mean", (DL_FUNC) &_RcppBandicoot_gpu_mean, 1},
    {"_RcppBandicoot_gpu_eye", (DL_FUNC) &_RcppBandicoot_gpu_eye, 1},
    {"_RcppBandicoot_gpu_randu", (DL_FUNC) &_RcppBandicoot_gpu_randu, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_RcppBandicoot(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
