# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Initialise the Bandicoot GPU runtime
#'
#' Selects and initialises a device for the backend this package was built
#' against. Bandicoot also initialises lazily on the first GPU call, so this
#' is only needed when you want the device chosen (and reported) up front.
#'
#' @param print_info Logical. Print the selected device's properties to the
#'   console. Default `FALSE`.
#' @return
#' `TRUE` if a device was selected, `FALSE` otherwise. Called for its side
#' effect of initialising the runtime.
#' @export
#' @examples
#' # gpu_initialize() is not called directly here: see gpu_available()'s
#' # example for why the GPU runtime may be probed at most once per R
#' # session; gpu_device_info() is used for that one probe.
#' if (is.null(getOption("rcppbandicoot.ex_info"))) {
#'   options(rcppbandicoot.ex_info = gpu_device_info())
#' }
#' .rcppbandicoot_ex_info <- getOption("rcppbandicoot.ex_info")
#' isTRUE(.rcppbandicoot_ex_info$available)
gpu_initialize <- function(print_info = FALSE) {
    .Call(`_RcppBandicoot_gpu_initialize`, print_info)
}

#' Is a usable GPU device available?
#'
#' Runs a one-element GPU operation and reports whether it succeeded. Unlike
#' [bandicoot_config()], which reports only what was detected at build time,
#' this answers the runtime question: is there a device, and can this build
#' actually reach its kernel sources?
#'
#' @return
#' `TRUE` if a device is present and a kernel executed, `FALSE` otherwise.
#' Never throws.
#' @export
#' @examples
#' # gpu_available() re-initialises the GPU runtime every time it is
#' # called, and Bandicoot's runtime must not be initialised more than once
#' # per R session (a second init leaves already-compiled kernels dangling
#' # and pointed at a freed context). Every example in this package
#' # therefore probes the device via gpu_device_info() at most once per
#' # session and reuses the cached result afterwards.
#' if (is.null(getOption("rcppbandicoot.ex_info"))) {
#'   options(rcppbandicoot.ex_info = gpu_device_info())
#' }
#' .rcppbandicoot_ex_info <- getOption("rcppbandicoot.ex_info")
#' isTRUE(.rcppbandicoot_ex_info$available)
gpu_available <- function() {
    .Call(`_RcppBandicoot_gpu_available`)
}

#' Report the selected GPU device's properties
#'
#' @return
#' A list with elements `available`, `backend` (`"opencl"`, `"cuda"` or
#' `"none"`), `fp64`, `fp16`, `subgroups`, `subgroup_size`, `n_units` and
#' `max_wg`. Never throws; on a machine with no device every capability is
#' reported as `FALSE`/zero.
#' @export
#' @examples
#' # See gpu_available()'s example for why this probe is cached and reused
#' # by every other example in this package.
#' if (is.null(getOption("rcppbandicoot.ex_info"))) {
#'   options(rcppbandicoot.ex_info = gpu_device_info())
#' }
#' .rcppbandicoot_ex_info <- getOption("rcppbandicoot.ex_info")
#' str(.rcppbandicoot_ex_info)
gpu_device_info <- function() {
    .Call(`_RcppBandicoot_gpu_device_info`)
}

#' Get Bandicoot version
#'
#' Prints the current version of the Bandicoot library.
#' @export
#' @examples
#' bandicoot_version()
bandicoot_version <- function() {
    invisible(.Call(`_RcppBandicoot_bandicoot_version`))
}

#' GPU Matrix Multiplication
#'
#' Multiply two matrices on the GPU using Bandicoot
#'
#' @param A First matrix
#' @param B Second matrix
#' @return Product of A and B computed on GPU
#' @export
#' @examples
#' # See gpu_available()'s example for why this probe is cached and reused
#' # by every other example in this package.
#' if (is.null(getOption("rcppbandicoot.ex_info"))) {
#'   options(rcppbandicoot.ex_info = gpu_device_info())
#' }
#' .rcppbandicoot_ex_info <- getOption("rcppbandicoot.ex_info")
#' .rcppbandicoot_ex_xfail <- strsplit(Sys.getenv("RCPPBANDICOOT_XFAIL"), ",", fixed = TRUE)[[1]]
#' # RCPPBANDICOOT_XFAIL lists operations known broken on this runner's
#' # device (see tests/testthat/helper-gpu.R); examples honour it too so
#' # R CMD check does not crash the R session running one.
#' if (isTRUE(.rcppbandicoot_ex_info$available) &&
#'     !("gpu_matrix_multiply" %in% .rcppbandicoot_ex_xfail)) {
#'   A <- matrix(c(1, 2, 3, 4), 2, 2)
#'   B <- matrix(c(5, 6, 7, 8), 2, 2)
#'   gpu_matrix_multiply(A, B)
#' }
gpu_matrix_multiply <- function(A, B) {
    .Call(`_RcppBandicoot_gpu_matrix_multiply`, A, B)
}

#' GPU Matrix Transpose
#'
#' Transpose a matrix on the GPU using Bandicoot
#'
#' @param A Matrix to transpose
#' @return Transposed matrix computed on GPU
#' @export
#' @examples
#' # See gpu_available()'s example for why this probe is cached and reused
#' # by every other example in this package.
#' if (is.null(getOption("rcppbandicoot.ex_info"))) {
#'   options(rcppbandicoot.ex_info = gpu_device_info())
#' }
#' .rcppbandicoot_ex_info <- getOption("rcppbandicoot.ex_info")
#' .rcppbandicoot_ex_xfail <- strsplit(Sys.getenv("RCPPBANDICOOT_XFAIL"), ",", fixed = TRUE)[[1]]
#' # RCPPBANDICOOT_XFAIL lists operations known broken on this runner's
#' # device (see tests/testthat/helper-gpu.R); examples honour it too so
#' # R CMD check does not crash the R session running one.
#' if (isTRUE(.rcppbandicoot_ex_info$available) &&
#'     !("gpu_transpose" %in% .rcppbandicoot_ex_xfail)) {
#'   gpu_transpose(matrix(1:6, nrow = 2))
#' }
gpu_transpose <- function(A) {
    .Call(`_RcppBandicoot_gpu_transpose`, A)
}

#' GPU Matrix Addition
#'
#' Add two matrices on the GPU using Bandicoot
#'
#' @param A First matrix
#' @param B Second matrix
#' @return Sum of A and B computed on GPU
#' @export
#' @examples
#' # See gpu_available()'s example for why this probe is cached and reused
#' # by every other example in this package.
#' if (is.null(getOption("rcppbandicoot.ex_info"))) {
#'   options(rcppbandicoot.ex_info = gpu_device_info())
#' }
#' .rcppbandicoot_ex_info <- getOption("rcppbandicoot.ex_info")
#' .rcppbandicoot_ex_xfail <- strsplit(Sys.getenv("RCPPBANDICOOT_XFAIL"), ",", fixed = TRUE)[[1]]
#' # RCPPBANDICOOT_XFAIL lists operations known broken on this runner's
#' # device (see tests/testthat/helper-gpu.R); examples honour it too so
#' # R CMD check does not crash the R session running one.
#' if (isTRUE(.rcppbandicoot_ex_info$available) &&
#'     !("gpu_matrix_add" %in% .rcppbandicoot_ex_xfail)) {
#'   gpu_matrix_add(matrix(c(1, 2, 3, 4), 2, 2), matrix(c(5, 6, 7, 8), 2, 2))
#' }
gpu_matrix_add <- function(A, B) {
    .Call(`_RcppBandicoot_gpu_matrix_add`, A, B)
}

#' GPU Element-wise Operations
#'
#' Apply element-wise square operation on GPU
#'
#' @param A Input matrix
#' @return Matrix with each element squared, computed on GPU
#' @export
#' @examples
#' # See gpu_available()'s example for why this probe is cached and reused
#' # by every other example in this package.
#' if (is.null(getOption("rcppbandicoot.ex_info"))) {
#'   options(rcppbandicoot.ex_info = gpu_device_info())
#' }
#' .rcppbandicoot_ex_info <- getOption("rcppbandicoot.ex_info")
#' .rcppbandicoot_ex_xfail <- strsplit(Sys.getenv("RCPPBANDICOOT_XFAIL"), ",", fixed = TRUE)[[1]]
#' # RCPPBANDICOOT_XFAIL lists operations known broken on this runner's
#' # device (see tests/testthat/helper-gpu.R); examples honour it too so
#' # R CMD check does not crash the R session running one.
#' if (isTRUE(.rcppbandicoot_ex_info$available) &&
#'     isTRUE(.rcppbandicoot_ex_info$fp64) &&
#'     !("gpu_element_square" %in% .rcppbandicoot_ex_xfail)) {
#'   gpu_element_square(matrix(c(1, 2, 3, 4), 2, 2))
#' }
gpu_element_square <- function(A) {
    .Call(`_RcppBandicoot_gpu_element_square`, A)
}

#' GPU Sum
#'
#' Calculate the sum of all elements in a matrix on GPU
#'
#' @param A Input matrix
#' @return Sum of all elements
#' @export
#' @examples
#' # See gpu_available()'s example for why this probe is cached and reused
#' # by every other example in this package.
#' if (is.null(getOption("rcppbandicoot.ex_info"))) {
#'   options(rcppbandicoot.ex_info = gpu_device_info())
#' }
#' .rcppbandicoot_ex_info <- getOption("rcppbandicoot.ex_info")
#' .rcppbandicoot_ex_xfail <- strsplit(Sys.getenv("RCPPBANDICOOT_XFAIL"), ",", fixed = TRUE)[[1]]
#' # RCPPBANDICOOT_XFAIL lists operations known broken on this runner's
#' # device (see tests/testthat/helper-gpu.R); examples honour it too so
#' # R CMD check does not crash the R session running one.
#' if (isTRUE(.rcppbandicoot_ex_info$available) &&
#'     !("gpu_sum" %in% .rcppbandicoot_ex_xfail)) {
#'   gpu_sum(matrix(1:6, nrow = 2))
#' }
gpu_sum <- function(A) {
    .Call(`_RcppBandicoot_gpu_sum`, A)
}

#' GPU Mean
#'
#' Calculate the mean of all elements in a matrix on GPU
#'
#' @param A Input matrix
#' @return Mean of all elements
#' @export
#' @examples
#' # See gpu_available()'s example for why this probe is cached and reused
#' # by every other example in this package.
#' if (is.null(getOption("rcppbandicoot.ex_info"))) {
#'   options(rcppbandicoot.ex_info = gpu_device_info())
#' }
#' .rcppbandicoot_ex_info <- getOption("rcppbandicoot.ex_info")
#' .rcppbandicoot_ex_xfail <- strsplit(Sys.getenv("RCPPBANDICOOT_XFAIL"), ",", fixed = TRUE)[[1]]
#' # RCPPBANDICOOT_XFAIL lists operations known broken on this runner's
#' # device (see tests/testthat/helper-gpu.R); examples honour it too so
#' # R CMD check does not crash the R session running one.
#' if (isTRUE(.rcppbandicoot_ex_info$available) &&
#'     !("gpu_mean" %in% .rcppbandicoot_ex_xfail)) {
#'   gpu_mean(matrix(1:6, nrow = 2))
#' }
gpu_mean <- function(A) {
    .Call(`_RcppBandicoot_gpu_mean`, A)
}

#' Create Identity Matrix on GPU
#'
#' Create an identity matrix on the GPU
#'
#' @param n Size of the identity matrix
#' @return n x n identity matrix on GPU
#' @export
#' @examples
#' # See gpu_available()'s example for why this probe is cached and reused
#' # by every other example in this package.
#' if (is.null(getOption("rcppbandicoot.ex_info"))) {
#'   options(rcppbandicoot.ex_info = gpu_device_info())
#' }
#' .rcppbandicoot_ex_info <- getOption("rcppbandicoot.ex_info")
#' .rcppbandicoot_ex_xfail <- strsplit(Sys.getenv("RCPPBANDICOOT_XFAIL"), ",", fixed = TRUE)[[1]]
#' # RCPPBANDICOOT_XFAIL lists operations known broken on this runner's
#' # device (see tests/testthat/helper-gpu.R); examples honour it too so
#' # R CMD check does not crash the R session running one.
#' if (isTRUE(.rcppbandicoot_ex_info$available) &&
#'     !("gpu_eye" %in% .rcppbandicoot_ex_xfail)) {
#'   gpu_eye(3)
#' }
gpu_eye <- function(n) {
    .Call(`_RcppBandicoot_gpu_eye`, n)
}

#' Create Random Matrix on GPU
#'
#' Create a matrix with random values on the GPU
#'
#' @param n_rows Number of rows
#' @param n_cols Number of columns
#' @return Random matrix on GPU
#' @export
#' @examples
#' # See gpu_available()'s example for why this probe is cached and reused
#' # by every other example in this package.
#' if (is.null(getOption("rcppbandicoot.ex_info"))) {
#'   options(rcppbandicoot.ex_info = gpu_device_info())
#' }
#' .rcppbandicoot_ex_info <- getOption("rcppbandicoot.ex_info")
#' .rcppbandicoot_ex_xfail <- strsplit(Sys.getenv("RCPPBANDICOOT_XFAIL"), ",", fixed = TRUE)[[1]]
#' # RCPPBANDICOOT_XFAIL lists operations known broken on this runner's
#' # device (see tests/testthat/helper-gpu.R); examples honour it too so
#' # R CMD check does not crash the R session running one.
#' if (isTRUE(.rcppbandicoot_ex_info$available) &&
#'     !("gpu_randu" %in% .rcppbandicoot_ex_xfail)) {
#'   dim(gpu_randu(4, 3))
#' }
gpu_randu <- function(n_rows, n_cols) {
    .Call(`_RcppBandicoot_gpu_randu`, n_rows, n_cols)
}

#' Set the Bandicoot kernel source directory
#'
#' Internal. Called from \code{.onLoad} with the installed location of the
#' bandicoot kernel sources so they resolve at run time regardless of where
#' the package was built. The trailing slash is required: Bandicoot appends
#' \code{"opencl/<file>"} to this path.
#'
#' @param path Directory holding the bandicoot kernel sources, with a
#'   trailing slash.
#' @return Invisibly \code{NULL}.
#' @keywords internal
set_kernel_source_dir <- function(path) {
    invisible(.Call(`_RcppBandicoot_set_kernel_source_dir`, path))
}

