# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Get Bandicoot version
#'
#' Prints the current version of the Bandicoot library.
#' @export
#' @examples
#' bandicoot_version()
bandicoot_version <- function() {
    invisible(.Call(`_RcppBandicoot_bandicoot_version`))
}

#' GPU Matrix Multiplication
#'
#' Multiply two matrices on the GPU using Bandicoot
#'
#' @param A First matrix
#' @param B Second matrix
#' @return Product of A and B computed on GPU
#' @export
gpu_matrix_multiply <- function(A, B) {
    .Call(`_RcppBandicoot_gpu_matrix_multiply`, A, B)
}

#' GPU Matrix Transpose
#'
#' Transpose a matrix on the GPU using Bandicoot
#'
#' @param A Matrix to transpose
#' @return Transposed matrix computed on GPU
#' @export
gpu_transpose <- function(A) {
    .Call(`_RcppBandicoot_gpu_transpose`, A)
}

#' GPU Matrix Addition
#'
#' Add two matrices on the GPU using Bandicoot
#'
#' @param A First matrix
#' @param B Second matrix
#' @return Sum of A and B computed on GPU
#' @export
gpu_matrix_add <- function(A, B) {
    .Call(`_RcppBandicoot_gpu_matrix_add`, A, B)
}

#' GPU Element-wise Operations
#'
#' Apply element-wise square operation on GPU
#'
#' @param A Input matrix
#' @return Matrix with each element squared, computed on GPU
#' @export
gpu_element_square <- function(A) {
    .Call(`_RcppBandicoot_gpu_element_square`, A)
}

#' GPU Sum
#'
#' Calculate the sum of all elements in a matrix on GPU
#'
#' @param A Input matrix
#' @return Sum of all elements
#' @export
gpu_sum <- function(A) {
    .Call(`_RcppBandicoot_gpu_sum`, A)
}

#' GPU Mean
#'
#' Calculate the mean of all elements in a matrix on GPU
#'
#' @param A Input matrix
#' @return Mean of all elements
#' @export
gpu_mean <- function(A) {
    .Call(`_RcppBandicoot_gpu_mean`, A)
}

#' Create Identity Matrix on GPU
#'
#' Create an identity matrix on the GPU
#'
#' @param n Size of the identity matrix
#' @return n x n identity matrix on GPU
#' @export
gpu_eye <- function(n) {
    .Call(`_RcppBandicoot_gpu_eye`, n)
}

#' Create Random Matrix on GPU
#'
#' Create a matrix with random values on the GPU
#'
#' @param n_rows Number of rows
#' @param n_cols Number of columns
#' @return Random matrix on GPU
#' @export
gpu_randu <- function(n_rows, n_cols) {
    .Call(`_RcppBandicoot_gpu_randu`, n_rows, n_cols)
}

