# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Version of the vendored Bandicoot library
#'
#' Reports the version of the Bandicoot C++ headers this package was compiled
#' against. The value is a compile-time constant, so no GPU device is touched
#' and the runtime is not initialised.
#'
#' @return
#' A length-one character vector holding the version as `"major.minor.patch"`.
#' @export
#' @examples
#' bandicoot_version()
#' package_version(bandicoot_version()) >= "4.0.0"
bandicoot_version <- function() {
    .Call(`_RcppBandicoot_bandicoot_version`)
}

#' Initialise the Bandicoot GPU runtime
#'
#' Selects and initialises a device for the backend this package was built
#' against. Bandicoot also initialises lazily on the first GPU call, so this
#' is only needed when you want the device chosen (and reported) up front.
#'
#' @param print_info Logical. Print the selected device's properties to the
#'   console. Default `FALSE`.
#' @return
#' `TRUE` if a device was selected, `FALSE` otherwise. Called for its side
#' effect of initialising the runtime.
#' @export
#' @examplesIf nzchar(Sys.getenv("RCPPBANDICOOT_RUN_GPU_EXAMPLES"))
#' gpu_initialize()
gpu_initialize <- function(print_info = FALSE) {
    .Call(`_RcppBandicoot_gpu_initialize`, print_info)
}

#' Is a usable GPU device available?
#'
#' Runs a one-element GPU operation and reports whether it succeeded. Unlike
#' [bandicoot_config()], which reports only what was detected at build time,
#' this answers the runtime question: is there a device, and can this build
#' actually reach its kernel sources?
#'
#' @return
#' `TRUE` if a device is present and a kernel executed, `FALSE` otherwise.
#' Never throws.
#' @export
#' @examplesIf nzchar(Sys.getenv("RCPPBANDICOOT_RUN_GPU_EXAMPLES"))
#' gpu_available()
gpu_available <- function() {
    .Call(`_RcppBandicoot_gpu_available`)
}

#' Report the selected GPU device's properties
#'
#' @return
#' A list with elements `available`, `backend` (`"opencl"`, `"cuda"` or
#' `"none"`), `fp64`, `fp16`, `subgroups`, `subgroup_size`, `n_units` and
#' `max_wg`. Never throws; on a machine with no device every capability is
#' reported as `FALSE`/zero.
#' @export
#' @examplesIf nzchar(Sys.getenv("RCPPBANDICOOT_RUN_GPU_EXAMPLES"))
#' str(gpu_device_info())
gpu_device_info <- function() {
    .Call(`_RcppBandicoot_gpu_device_info`)
}

#' GPU Matrix Multiplication
#'
#' Multiply two matrices on the GPU using Bandicoot
#'
#' @param A First matrix
#' @param B Second matrix
#' @return Product of A and B computed on GPU
#' @section Precision:
#' The product is computed in single precision (`float`). R's doubles are
#' rounded on the way to the device and the result is widened back, so
#' expect a relative error around `1e-7` against `A %*% B` in base R, growing
#' with the shared inner dimension as the rounding accumulates.
#' @export
#' @examplesIf nzchar(Sys.getenv("RCPPBANDICOOT_RUN_GPU_EXAMPLES"))
#' A <- matrix(c(1, 2, 3, 4), 2, 2)
#' B <- matrix(c(5, 6, 7, 8), 2, 2)
#' gpu_matrix_multiply(A, B)
gpu_matrix_multiply <- function(A, B) {
    .Call(`_RcppBandicoot_gpu_matrix_multiply`, A, B)
}

#' GPU Matrix Transpose
#'
#' Transpose a matrix on the GPU using Bandicoot
#'
#' @param A Matrix to transpose
#' @return Transposed matrix computed on GPU
#' @section Precision:
#' The matrix is held on the device in single precision (`float`).
#' Transposition only moves elements, but the round trip through `float`
#' rounds every one of them, so entries needing more than about 7 significant
#' decimal digits do not come back bit-identical to the input.
#' @export
#' @examplesIf nzchar(Sys.getenv("RCPPBANDICOOT_RUN_GPU_EXAMPLES"))
#' gpu_transpose(matrix(1:6, nrow = 2))
gpu_transpose <- function(A) {
    .Call(`_RcppBandicoot_gpu_transpose`, A)
}

#' GPU Matrix Addition
#'
#' Add two matrices on the GPU using Bandicoot
#'
#' @param A First matrix
#' @param B Second matrix
#' @return Sum of A and B computed on GPU
#' @section Precision:
#' The sum is computed in single precision (`float`). R's doubles are rounded
#' on the way to the device and the result is widened back, so expect a
#' relative error around `1e-7` against `A + B` in base R.
#' @export
#' @examplesIf nzchar(Sys.getenv("RCPPBANDICOOT_RUN_GPU_EXAMPLES"))
#' gpu_matrix_add(matrix(c(1, 2, 3, 4), 2, 2), matrix(c(5, 6, 7, 8), 2, 2))
gpu_matrix_add <- function(A, B) {
    .Call(`_RcppBandicoot_gpu_matrix_add`, A, B)
}

#' GPU Element-wise Operations
#'
#' Apply element-wise square operation on GPU
#'
#' @param A Input matrix
#' @return Matrix with each element squared, computed on GPU
#' @section Precision:
#' This is the only operation in the package that runs in double precision
#' (`double`), so the result matches `A^2` in base R to full double accuracy.
#' It therefore needs a device with 64-bit floating point support: check
#' `gpu_device_info()$fp64` before calling, as the OpenCL backend requires the
#' `cl_khr_fp64` extension.
#' @export
#' @examplesIf nzchar(Sys.getenv("RCPPBANDICOOT_RUN_GPU_EXAMPLES"))
#' gpu_element_square(matrix(c(1, 2, 3, 4), 2, 2))
gpu_element_square <- function(A) {
    .Call(`_RcppBandicoot_gpu_element_square`, A)
}

#' GPU Sum
#'
#' Calculate the sum of all elements in a matrix on GPU
#'
#' @param A Input matrix
#' @return Sum of all elements
#' @section Precision:
#' The matrix is held and accumulated in single precision (`float`) even
#' though the value handed back to R is a double, so the sum carries about 7
#' significant decimal digits rather than 16. Expect a relative error around
#' `1e-7` against `sum(A)`, growing with the number of elements accumulated.
#' @export
#' @examplesIf nzchar(Sys.getenv("RCPPBANDICOOT_RUN_GPU_EXAMPLES"))
#' gpu_sum(matrix(1:6, nrow = 2))
gpu_sum <- function(A) {
    .Call(`_RcppBandicoot_gpu_sum`, A)
}

#' GPU Mean
#'
#' Calculate the mean of all elements in a matrix on GPU
#'
#' @param A Input matrix
#' @return Mean of all elements
#' @section Precision:
#' The matrix is held and averaged in single precision (`float`) even though
#' the value handed back to R is a double, so the mean carries about 7
#' significant decimal digits rather than 16. Expect a relative error around
#' `1e-7` against `mean(A)`.
#' @export
#' @examplesIf nzchar(Sys.getenv("RCPPBANDICOOT_RUN_GPU_EXAMPLES"))
#' gpu_mean(matrix(1:6, nrow = 2))
gpu_mean <- function(A) {
    .Call(`_RcppBandicoot_gpu_mean`, A)
}

#' Create Identity Matrix on GPU
#'
#' Create an identity matrix on the GPU
#'
#' @param n Size of the identity matrix
#' @return n x n identity matrix on GPU
#' @section Precision:
#' The matrix is created in single precision (`float`). Zero and one are both
#' exact in `float`, so the result is exact.
#' @export
#' @examplesIf nzchar(Sys.getenv("RCPPBANDICOOT_RUN_GPU_EXAMPLES"))
#' gpu_eye(3)
gpu_eye <- function(n) {
    .Call(`_RcppBandicoot_gpu_eye`, n)
}

#' Set the GPU random number generator seed
#'
#' Seeds the device-side generator that backs [gpu_randu()]. Bandicoot
#' defaults that seed to `0` and never randomises it, so without an explicit
#' seed every fresh process would draw the same numbers.
#'
#' @param seed Seed for the device generator: a non-negative whole number no
#'   larger than `2^53`. R has no unsigned 64-bit type, so the seed arrives as
#'   a double and is converted to the 64-bit unsigned value Bandicoot wants;
#'   `2^53` is the largest integer a double still represents exactly.
#' @return Invisibly `NULL`. Called for its side effect on the device
#'   generator.
#' @seealso [gpu_randu()], which seeds the device from R's own random number
#'   stream on the first draw of a session when this has not been called.
#' @export
#' @examplesIf nzchar(Sys.getenv("RCPPBANDICOOT_RUN_GPU_EXAMPLES"))
#' gpu_set_seed(42)
#' gpu_randu(2, 2)
gpu_set_seed <- function(seed) {
    invisible(.Call(`_RcppBandicoot_gpu_set_seed`, seed))
}

#' Create Random Matrix on GPU
#'
#' Create a matrix with uniformly distributed random values on the GPU
#'
#' @param n_rows Number of rows
#' @param n_cols Number of columns
#' @return Random matrix on GPU
#' @section Seeding:
#' Bandicoot defaults the device generator's seed to `0` and never randomises
#' it, so on its own this function would return the same matrix in every fresh
#' R process. To avoid that, the *first* GPU random draw in a session takes its
#' seed from R's own random number stream; later draws continue from wherever
#' the device generator left off. Two consequences follow: `set.seed()` before
#' that first draw makes the whole session reproducible, and drawing that seed
#' consumes two values from R's stream. Call [gpu_set_seed()] to override the
#' seed explicitly instead, at any point including before the first draw.
#' @section Precision:
#' Values are generated in single precision (`float`) and widened to doubles on
#' the way back to R. The draws therefore take roughly `2^24` distinct values
#' in `[0, 1)` rather than the far finer grid `runif()` produces.
#' @export
#' @examplesIf nzchar(Sys.getenv("RCPPBANDICOOT_RUN_GPU_EXAMPLES"))
#' dim(gpu_randu(4, 3))
gpu_randu <- function(n_rows, n_cols) {
    .Call(`_RcppBandicoot_gpu_randu`, n_rows, n_cols)
}

#' Set the Bandicoot kernel source directory
#'
#' Internal. Called from \code{.onLoad} with the installed location of the
#' bandicoot kernel sources so they resolve at run time regardless of where
#' the package was built. The trailing slash is required: Bandicoot appends
#' \code{"opencl/<file>"} to this path.
#'
#' @param path Directory holding the bandicoot kernel sources, with a
#'   trailing slash.
#' @return Invisibly \code{NULL}.
#' @keywords internal
set_kernel_source_dir <- function(path) {
    invisible(.Call(`_RcppBandicoot_set_kernel_source_dir`, path))
}

#' Get the Bandicoot kernel source directory
#'
#' Internal. Reports the path the compiled code will actually hand to
#' Bandicoot when it loads a kernel, which is the value \code{.onLoad} last
#' wrote. It exists so the tests can assert on the compiled state directly:
#' checking an independently recomputed \code{system.file()} path proves
#' nothing about what the shared object holds, so a \code{.onLoad} regression
#' would leave every GPU test skipping and the suite green.
#'
#' @return
#' A length-one character vector holding the directory, with a trailing slash.
#' Empty only if the package was built without a configure-time default and
#' \code{.onLoad} has not run.
#' @keywords internal
get_kernel_source_dir <- function() {
    .Call(`_RcppBandicoot_get_kernel_source_dir`)
}

